In [1]:
#Connect to cleaned_sample.db using sqlite3.
import sqlite3

db = sqlite3.connect("C:\\Users\\JehyeonHeo\\sqlite_windows\\small_samples.db")
c = db.cursor()

In [2]:
#query about postcodes in cleaned files.
query = "select tags.value, count(*) as count \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'postcode' \
        group by tags.value \
        order by count desc;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('10314', 75)
('11234', 75)
('10312', 58)
('10306', 55)
('11706', 54)
('11743', 52)
('11236', 49)
('11385', 49)
('11223', 47)
('11757', 47)
('11207', 45)
('10469', 41)
('11746', 40)
('10465', 36)
('11208', 36)
('11357', 36)
('10304', 35)
('10305', 35)
('11219', 35)
('11203', 34)
('11229', 34)
('11413', 34)
('11704', 34)
('11204', 33)
('11220', 33)
('11434', 33)
('11731', 33)
('11221', 32)
('11420', 32)
('11214', 31)
('11364', 31)
('11375', 31)
('10461', 30)
('11412', 30)
('10309', 29)
('10466', 29)
('11210', 29)
('11233', 29)
('11358', 29)
('11215', 28)
('11228', 28)
('11235', 28)
('11373', 28)
('11378', 28)
('11379', 28)
('11725', 28)
('10308', 27)
('11209', 27)
('11218', 27)
('11377', 27)
('11717', 27)
('11729', 27)
('11365', 26)
('11419', 26)
('10301', 25)
('11230', 25)
('11355', 25)
('11701', 24)
('11361', 23)
('11421', 23)
('11435', 23)
('11768', 23)
('11795', 23)
('10310', 22)
('11216', 22)
('11367', 22)
('11368', 22)
('11432', 22)
('11691', 22)
('11702', 22)
('11105', 21)
('11422', 21)
('10303', 20)
('11222', 20)
('11423', 20)
('11429', 20)
('10462', 19)
('11211', 19)
('11212', 19)
('11213', 19)
('11231', 19)
('11414', 19)
('10467', 18)
('11217', 18)
('11417', 18)
('11433', 18)
('11103', 17)
('11226', 17)
('11369', 17)
('10473', 16)
('11106', 16)
('11225', 16)
('11238', 16)
('11411', 16)
('11416', 16)
('11418', 16)
('11426', 16)
('11703', 16)
('11726', 16)
('10472', 15)
('11101', 15)
('11354', 15)
('11356', 15)
('11362', 15)
('11428', 15)
('11436', 15)
('11370', 14)
('11372', 14)
('10014', 13)
('11427', 13)
('11694', 13)
('11754', 13)
('10458', 12)
('11004', 12)
('11201', 12)
('11206', 12)
('11224', 12)
('11232', 12)
('11374', 12)
('11740', 12)
('11747', 12)
('10022', 11)
('10025', 11)
('10307', 11)
('10460', 11)
('11102', 11)
('11798', 11)
('10002', 10)
('10302', 10)
('10451', 10)
('10457', 10)
('10459', 10)
('11237', 10)
('11360', 10)
('11366', 10)
('11787', 10)
('10001', 9)
('10027', 9)
('10029', 9)
('10033', 9)
('10463', 9)
('11205', 9)
('10011', 8)
('10016', 8)
('10028', 8)
('10453', 8)
('10454', 8)
('10456', 8)
('11104', 8)
('11415', 8)
('11697', 8)
('11721', 8)
('10023', 7)
('10024', 7)
('10031', 7)
('10035', 7)
('10468', 7)
('10470', 7)
('11735', 7)
('10003', 6)
('10013', 6)
('10021', 6)
('10065', 6)
('10455', 6)
('10471', 6)
('10474', 6)
('11249', 6)
('11692', 6)
('10012', 5)
('10018', 5)
('10032', 5)
('10034', 5)
('10037', 5)
('10128', 5)
('10452', 5)
('10475', 5)
('11363', 5)
('11693', 5)
('10009', 4)
('10017', 4)
('10019', 4)
('10026', 4)
('10036', 4)
('10464', 4)
('11788', 4)
('10030', 3)
('10038', 3)
('11040', 3)
('11560', 3)
('11724', 3)
('08816', 2)
('10006', 2)
('10040', 2)
('11718', 2)
('07030', 1)
('07036', 1)
('07042', 1)
('07043', 1)
('07083', 1)
('07111', 1)
('07302', 1)
('07444', 1)
('07902', 1)
('08854-8039', 1)
('08901', 1)
('08901-1904', 1)
('10004', 1)
('10007', 1)
('10010', 1)
('10039', 1)
('10075', 1)
('10591', 1)
('11001', 1)
('11005', 1)
('11050', 1)
('11722', 1)
('11751', 1)
('11765', 1)

In [3]:
#query about postcodes in uncleaned files.
query = "select tags.value, count(*) as count \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'postcode' \
        group by tags.value \
        order by count desc;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('10314', 75)
('11234', 75)
('10312', 58)
('10306', 55)
('11706', 54)
('11743', 52)
('11236', 49)
('11385', 49)
('11223', 47)
('11757', 47)
('11207', 45)
('10469', 41)
('11746', 40)
('10465', 36)
('11208', 36)
('11357', 36)
('10304', 35)
('10305', 35)
('11219', 35)
('11203', 34)
('11229', 34)
('11413', 34)
('11704', 34)
('11204', 33)
('11220', 33)
('11434', 33)
('11731', 33)
('11221', 32)
('11420', 32)
('11214', 31)
('11364', 31)
('11375', 31)
('10461', 30)
('11412', 30)
('10309', 29)
('10466', 29)
('11210', 29)
('11233', 29)
('11358', 29)
('11215', 28)
('11228', 28)
('11235', 28)
('11373', 28)
('11378', 28)
('11379', 28)
('11725', 28)
('10308', 27)
('11209', 27)
('11218', 27)
('11377', 27)
('11717', 27)
('11729', 27)
('11365', 26)
('11419', 26)
('10301', 25)
('11230', 25)
('11355', 25)
('11701', 24)
('11361', 23)
('11421', 23)
('11435', 23)
('11768', 23)
('11795', 23)
('10310', 22)
('11216', 22)
('11367', 22)
('11368', 22)
('11432', 22)
('11691', 22)
('11702', 22)
('11105', 21)
('11422', 21)
('10303', 20)
('11222', 20)
('11423', 20)
('11429', 20)
('10462', 19)
('11211', 19)
('11212', 19)
('11213', 19)
('11231', 19)
('11414', 19)
('10467', 18)
('11217', 18)
('11417', 18)
('11433', 18)
('11103', 17)
('11226', 17)
('11369', 17)
('10473', 16)
('11106', 16)
('11225', 16)
('11238', 16)
('11411', 16)
('11416', 16)
('11418', 16)
('11426', 16)
('11703', 16)
('11726', 16)
('10472', 15)
('11101', 15)
('11354', 15)
('11356', 15)
('11362', 15)
('11428', 15)
('11436', 15)
('11370', 14)
('11372', 14)
('10014', 13)
('11427', 13)
('11694', 13)
('11754', 13)
('10458', 12)
('11004', 12)
('11201', 12)
('11206', 12)
('11224', 12)
('11232', 12)
('11374', 12)
('11740', 12)
('11747', 12)
('10022', 11)
('10025', 11)
('10307', 11)
('10460', 11)
('11102', 11)
('11798', 11)
('10002', 10)
('10302', 10)
('10451', 10)
('10457', 10)
('10459', 10)
('11237', 10)
('11360', 10)
('11366', 10)
('11787', 10)
('10001', 9)
('10027', 9)
('10029', 9)
('10033', 9)
('10463', 9)
('11205', 9)
('10011', 8)
('10016', 8)
('10028', 8)
('10453', 8)
('10454', 8)
('10456', 8)
('11104', 8)
('11415', 8)
('11697', 8)
('11721', 8)
('10023', 7)
('10024', 7)
('10031', 7)
('10035', 7)
('10468', 7)
('10470', 7)
('11735', 7)
('10003', 6)
('10013', 6)
('10021', 6)
('10065', 6)
('10455', 6)
('10471', 6)
('10474', 6)
('11249', 6)
('11692', 6)
('10012', 5)
('10018', 5)
('10032', 5)
('10034', 5)
('10037', 5)
('10128', 5)
('10452', 5)
('10475', 5)
('11363', 5)
('11693', 5)
('10009', 4)
('10017', 4)
('10019', 4)
('10026', 4)
('10036', 4)
('10464', 4)
('11788', 4)
('10030', 3)
('10038', 3)
('11040', 3)
('11560', 3)
('11724', 3)
('08816', 2)
('10006', 2)
('10040', 2)
('11718', 2)
('07030', 1)
('07036', 1)
('07042', 1)
('07043', 1)
('07083', 1)
('07111', 1)
('07302', 1)
('07444', 1)
('07902', 1)
('08854-8039', 1)
('08901', 1)
('08901-1904', 1)
('10004', 1)
('10007', 1)
('10010', 1)
('10039', 1)
('10075', 1)
('10591', 1)
('11001', 1)
('11005', 1)
('11050', 1)
('11722', 1)
('11751', 1)
('11765', 1)
('320', 1)

In [4]:
#query about websites in cleaned files.
query = "select distinct tags.value \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'website' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('http://brookwoodatbayshore.com',)
('http://citibikenyc.com',)
('http://davoodzadehrugs.com',)
('http://location.ctownsupermarkets.com/ny/jamaica/41-003/',)
('http://maps.google.com/local_url?dq=mi+Ranchito+Restaurant&q=http://www.miranchitogrillandbar.com/&oi=miw&sa=X&ct=miw_link&cd=1&cad=homepage,cid:1706131537235801532&ei=54vDUaLkB6fRxAGmtYDgBA&s=ANYYN7kQV_99A5w0y593WxyjRp5MfpJp2Q',)
('http://web.mta.info/nyct/service/bus/qnsche.htm',)
('http://www.dallasbbq.com',)
('http://www.dreamhotels.com/hotels/new-york/new-york/dream-downtown/hotel-overview',)
('http://www.dustyrosevintage.com',)
('http://www.jjay.cuny.edu/',)
('http://www.marrakechhotelnyc.com/',)
('http://www.nellyspillanes.com',)
('http://www.nyctacos.com/',)
('http://www.stagneschurchnyc.org',)
('http://www.thebeekmanpub.com/',)
('http://www.themexsoft.com',)
('http://www.whitecastle.com/locations/358',)
('https://www.shakeshack.com',)

In [5]:
#query about websites in uncleaned files.
query = "select distinct tags.value \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'website' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('brookwoodatbayshore.com',)
('http://citibikenyc.com',)
('http://davoodzadehrugs.com',)
('http://location.ctownsupermarkets.com/ny/jamaica/41-003/',)
('http://maps.google.com/local_url?dq=mi+Ranchito+Restaurant&q=http://www.miranchitogrillandbar.com/&oi=miw&sa=X&ct=miw_link&cd=1&cad=homepage,cid:1706131537235801532&ei=54vDUaLkB6fRxAGmtYDgBA&s=ANYYN7kQV_99A5w0y593WxyjRp5MfpJp2Q',)
('http://web.mta.info/nyct/service/bus/qnsche.htm',)
('http://www.dreamhotels.com/hotels/new-york/new-york/dream-downtown/hotel-overview',)
('http://www.dustyrosevintage.com',)
('http://www.jjay.cuny.edu/',)
('http://www.marrakechhotelnyc.com/',)
('http://www.nellyspillanes.com',)
('http://www.nyctacos.com/',)
('http://www.stagneschurchnyc.org',)
('http://www.thebeekmanpub.com/',)
('http://www.themexsoft.com',)
('http://www.whitecastle.com/locations/358',)
('https://www.shakeshack.com',)
('www.dallasbbq.com',)

In [6]:
#query about phones in cleaned files.
query = "select distinct tags.value \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'phone' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('(205) 900-7007',)
('(212) 222-2954',)
('(212) 268-5876',)
('(212) 462-0001',)
('(212) 749-1111',)
('(212) 792-9673',)
('(212) 874-4000',)
('(718) 482-7088',)
('(718) 657-0722',)

In [7]:
#query about phones in uncleaned files.
query = "select distinct tags.value \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'phone' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('+1 205 9007007',)
('+1 212 2222954',)
('+1 212 749 1111',)
('+1 212 874 4000',)
('+1-212-268-5876',)
('+1-212.462.0001',)
('+1-718-657-0722',)
('+12127929673',)
('1 718 482 7088',)

In [8]:
#query about faxs in cleaned files.
query = "select distinct tags.value \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'fax' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('(212) 268-0847',)
('(212) 678-6842',)

In [9]:
#query about faxs in uncleaned files.
query = "select distinct tags.value \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'fax' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('+1 212 678 6842',)
('+1-212-268-0847',)

In [10]:
#query about Faxs in cleaned files.
query = "select distinct tags.value \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'Fax' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

In [11]:
#query about Faxs in uncleaned files.
query = "select distinct tags.value \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'Fax' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

In [12]:
#query about maxspeed in cleaned files.
query = "select distinct tags.value \
        from (select * from nodes_tags \
                union all \
                select * from ways_tags) tags \
        where tags.key = 'maxspeed' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('15 mph',)
('160 mph',)
('20 mph',)
('201 mph',)
('25 mph',)
('30 mph',)
('35 mph',)
('40 mph',)
('45 mph',)
('50 mph',)
('55 mph',)
('65 mph',)
('70 mph',)
('Amtrak ETT 2010-01-18 mph',)
('signals mph',)

In [13]:
#query about maxspeed in uncleaned files.
query = "select distinct tags.value \
        from (select * from uncleaned_nodes_tags \
                union all \
                select * from uncleaned_ways_tags) tags \
        where tags.key = 'maxspeed' \
        order by tags.value;"
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('15',)
('15 mph',)
('160',)
('20 mph',)
('201',)
('25 mph',)
('30 mph',)
('35 mph',)
('40 mph',)
('45 mph',)
('50 mph',)
('55 mph',)
('65 mph',)
('70 mph',)
('Amtrak ETT 2010-01-18',)
('signals',)